-- give all the telephone numbers and names for all the owners of artworks stored in one specific gallery
CREATE VIEW TASK1KL AS (
	SELECT OWNERS.TELEPHONE_NUMBER, OWNERS.NAME_OF_THE_OWNER, GALLERIES.NAME_OF_THE_GALLERY
	FROM OWNERS
	JOIN CONTRACTS ON OWNERS.ID_OWNERS = CONTRACTS.ID_OWNERS
	JOIN GALLERIES ON CONTRACTS.NAME_OF_THE_GALLERY = GALLERIES.NAME_OF_THE_GALLERY
	WHERE GALLERIES.NAME_OF_THE_GALLERY = 'The Metropolian Museum of Art'
);

-- give names of all authors whose artworks are stored in specific city
SELECT NAME_OF_THE_AUTHOR, CITY
FROM ARTWORKS
JOIN AUTHORS ON ARTWORKS.ID_AUTHORS = AUTHORS.ID_AUTHORS 
JOIN STORED ON STORED.NAME_OF_THE_ARTWORK = ARTWORKS.NAME_OF_THE_ARTWORK
JOIN GALLERIES ON GALLERIES.NAME_OF_THE_GALLERY = STORED.NAME_OF_THE_GALLERY
WHERE GALLERIES.CITY = 'Paris';

-- sort artworks sold in particular city, display price, date of auction, name of the gallery and city 
SELECT S.LAST_PRICE, A.DATE_OF_AUCTION, G.NAME_OF_THE_GALLERY, G.CITY
FROM STARTING_PRICE AS S
JOIN AUCTIONS AS A ON S.ID_AUCTIONS = A.ID_AUCTIONS
JOIN GALLERIES AS G ON G.NAME_OF_THE_GALLERY = A.NAME_OF_THE_GALLERY
WHERE G.CITY = 'New York'
ORDER BY S.LAST_PRICE DESC;



--select auction which took place in 2022 with the greatest number of guests that appeared.
SELECT TOP 1 NAME_OF_THE_GALLERY, ID_AUCTIONS, GUESTS_APPEARED, DATE_OF_AUCTION
FROM AUCTIONS
WHERE YEAR(DATE_OF_AUCTION) = '2022'
ORDER BY GUESTS_APPEARED DESC;

--sum all the prices at which the art was sold in auctions in 2022
SELECT SUM(ST.LAST_PRICE) AS TOTAL_SALES_OF_ARTWORK_IN_2022, YEAR(A.DATE_OF_AUCTION) AS YEAR_OF_SALES
FROM STARTING_PRICE AS ST
JOIN AUCTIONS AS A ON ST.ID_AUCTIONS = A.ID_AUCTIONS
WHERE YEAR(A.DATE_OF_AUCTION) = '2022'
GROUP BY YEAR(A.DATE_OF_AUCTION);

--show the name of the artwork which difference between its starting and final price during an auction was the greatest.
SELECT TOP 1 ART.NAME_OF_THE_ARTWORK, (ST.LAST_PRICE - ST.STARTING_PRICE) AS LAST_PRICE_MINUS_STARTING_PRICE
FROM STARTING_PRICE AS ST
JOIN AUCTIONS AS A ON ST.ID_AUCTIONS = A.ID_AUCTIONS
JOIN GALLERIES AS G ON G.NAME_OF_THE_GALLERY = A.NAME_OF_THE_GALLERY
JOIN STORED AS S ON G.NAME_OF_THE_GALLERY = S.NAME_OF_THE_GALLERY
JOIN ARTWORKS AS ART ON ART.NAME_OF_THE_ARTWORK = S.NAME_OF_THE_ARTWORK
ORDER BY (ST.LAST_PRICE - ST.STARTING_PRICE) DESC;



-- give 5 names of people who proposed the most money in one offer in 2022
SELECT TOP 5 NAME_OF_PARTICIPANT, PRICE 
FROM PARTICIPANTS 
JOIN OFFERS ON PARTICIPANTS.ID_PARTICIPANTS = OFFERS.ID_PARTICIPANTS 
JOIN AUCTIONS ON OFFERS.ID_AUCTIONS = AUCTIONS.ID_AUCTIONS 
WHERE YEAR(DATE_OF_AUCTION) = '2022' 
ORDER BY PRICE DESC;

-- group authors of particular style of art (impressionism) that were stored in galleries
SELECT COUNT(ARTWORKS.NAME_OF_THE_ARTWORK) AS NUMBER_OF_ARTWORKS, AUTHORS.NAME_OF_THE_AUTHOR
FROM ARTWORKS 
JOIN AUTHORS ON ARTWORKS.ID_AUTHORS = AUTHORS.ID_AUTHORS 
JOIN STORED ON ARTWORKS.NAME_OF_THE_ARTWORK = STORED.NAME_OF_THE_ARTWORK 
JOIN GALLERIES ON STORED.NAME_OF_THE_GALLERY = GALLERIES.NAME_OF_THE_GALLERY 
WHERE ARTWORKS.STYLE = 'impressionism'
GROUP BY AUTHORS.NAME_OF_THE_AUTHOR;

-- sort people by the amount of money spent on artworks
SELECT NAME_OF_THE_OWNER, SUM(PRICE) AS TOTAL_MONEY_SPENT
FROM TRANSACTIONS 
JOIN OFFERS ON TRANSACTIONS.ID_OFFERS = OFFERS.ID_OFFERS 
JOIN PARTICIPANTS ON OFFERS.ID_PARTICIPANTS = PARTICIPANTS.ID_PARTICIPANTS 
JOIN CONTRACTS ON TRANSACTIONS.NAME_OF_THE_GALLERY = CONTRACTS.NAME_OF_THE_GALLERY
JOIN OWNERS ON CONTRACTS.ID_OWNERS = OWNERS.ID_OWNERS 
GROUP BY NAME_OF_THE_OWNER 
ORDER BY SUM(PRICE) DESC;