CREATE TABLE GALLERIES (
NAME_OF_THE_GALLERY VARCHAR(50) NOT NULL PRIMARY KEY,
CITY VARCHAR(50) NOT NULL,
NUMBER_OF_ARTWORKS_STORED INT,
SOLD_ARTWORKS INT
);

CREATE TABLE AUTHORS (
ID_AUTHORS INT NOT NULL PRIMARY KEY,
DATE_OF_BIRTH DATE NOT NULL,
DATE_OF_DEATH DATE,
NAME_OF_THE_AUTHOR VARCHAR(50) NOT NULL
);

CREATE TABLE ARTWORKS (
NAME_OF_THE_ARTWORK VARCHAR(50) NOT NULL PRIMARY KEY,
DATE_OF_CREATION DATE NOT NULL,
STYLE VARCHAR(50) NOT NULL,
ID_AUTHORS INT NOT NULL REFERENCES AUTHORS
);

CREATE TABLE STORED (
ID_STORED INT NOT NULL PRIMARY KEY,
STARTING_DATE_OF_STORAGE DATE NOT NULL,
ENDING_DATE_OF_STORAGE DATE,
NAME_OF_THE_GALLERY VARCHAR(50) NOT NULL REFERENCES GALLERIES,
NAME_OF_THE_ARTWORK VARCHAR(50) NOT NULL REFERENCES ARTWORKS
);

CREATE TABLE OWNERS (
ID_OWNERS INT NOT NULL PRIMARY KEY,
NAME_OF_THE_OWNER VARCHAR(50) NOT NULL,
TELEPHONE_NUMBER INT
);

CREATE TABLE CONTRACTS (
ID_CONTRACTS INT NOT NULL PRIMARY KEY,
STARTING_DATE_OF_STORING DATE NOT NULL,
ENDING_DATE_OF_STORING DATE NOT NULL,
NAME_OF_THE_GALLERY VARCHAR(50) NOT NULL REFERENCES GALLERIES,
NAME_OF_THE_ARTWORK VARCHAR(50) NOT NULL REFERENCES ARTWORKS,
ID_OWNERS INT NOT NULL REFERENCES OWNERS
);

CREATE TABLE AUCTIONS (
ID_AUCTIONS INT NOT NULL PRIMARY KEY,
DATE_OF_AUCTION DATE NOT NULL,
STARTED_AT_HOUR TIME NOT NULL,
ENDED_AT_HOUR TIME NOT NULL,
SALES_MADE INT,
GUESTS_INVITED INT,
GUESTS_APPEARED INT,
NAME_OF_THE_GALLERY VARCHAR(50) NOT NULL REFERENCES GALLERIES
);

CREATE TABLE STARTING_PRICE (
ID_STARTING_PRICE INT NOT NULL PRIMARY KEY,
STARTING_PRICE INT NOT NULL,
LAST_PRICE INT NOT NULL,
HOUR_OF_THE_BID TIME,
ID_AUCTIONS INT NOT NULL REFERENCES AUCTIONS
);

CREATE TABLE PARTICIPANTS (
ID_PARTICIPANTS INT NOT NULL PRIMARY KEY,
NAME_OF_PARTICIPANT VARCHAR(50) NOT NULL,
COUNTRY VARCHAR(50) NOT NULL,
TELEPHONE_NUMBER INT NOT NULL
);

CREATE TABLE OFFERS (
ID_OFFERS INT PRIMARY KEY NOT NULL,
PRICE INT NOT NULL,
ID_PARTICIPANTS INT NOT NULL REFERENCES PARTICIPANTS
);

CREATE TABLE TRANSACTIONS (
ID_TRANSACTIONS INT NOT NULL PRIMARY KEY,
DATE_OF_TRANSACTION DATE NOT NULL,
TIME_OF_TRANSACTION TIME,
ID_PARTICIPANTS INT NOT NULL REFERENCES PARTICIPANTS,
NAME_OF_THE_GALLERY VARCHAR(50) NOT NULL REFERENCES GALLERIES,
ID_OFFERS INT NOT NULL REFERENCES OFFERS
);