delete from CONTRACTS where CONTRACTS.NAME_OF_THE_GALLERY like '%Lisson Gallery%'
delete STARTING_PRICE where STARTING_PRICE.STARTING_PRICE <= 200
delete from TRANSACTIONS where DATEPART(year, TRANSACTIONS.DATE_OF_TRANSACTION) >= 2022
delete from STORED where STORED.NAME_OF_THE_GALLERY like '%louvre%'


update CONTRACTS
set ENDING_DATE_OF_STORING = '2022-12-20'
where ID_OWNERS = '3'

update STARTING_PRICE
set STARTING_PRICE = '250'
where STARTING_PRICE = '230'

update TRANSACTIONS
set DATE_OF_TRANSACTION = '2020-10-15'
where ID_PARTICIPANTS = '1'

update STORED
set NAME_OF_THE_GALLERY = 'Van Gogh Museum'
where NAME_OF_THE_ARTWORK = 'The Bedroom'